### ISSUE TITLE
Problems with markdown-style **strong** text

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll-compiler#19]
A few experiments:

- `**p a**`: fails (`Uncaught TypeError: children.map is not a function`)
- `**f a**`: succeeds
- `**pa**`: succeeds
- `**a**`: rendered as bulleted list with string content `*a**`
- `Test **p a**`: fails (`Uncaught TypeError: children.map is not a function`)
- `Test **f a**`: succeeds
- `Test **pa**`: succeeds
- `Test **a**`: suceeds (note starting the line with *not* `*` lets it know it's not a list)

In particular, the problem with the letter `p` is a bit surprising. I haven't tried all letters exhaustively yet. 😄

**Comment by mathisonian** [comment]
This should be fixed in `v1.3.1` via https://github.com/idyll-lang/idyll-compiler/commit/0e62942db7e398f0949f4cc1f7dda494c5247dff
