### ISSUE TITLE
Inconsistent space after component, depending on usage

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll-compiler#21]
`[Equation]foo[/Equation], bar` renders as `foo, bar` while `[Equation latex:"foo"/], bar` renders as `foo , bar`.

**Comment by mathisonian** [comment]
Can you give a larger example where this is happening? I'm seeing trailing space everywhere:

<img width="227" alt="screen shot 2017-05-21 at 2 36 37 pm" src="https://cloud.githubusercontent.com/assets/1074773/26287557/f80952fc-3e32-11e7-9e97-4356dafa2251.png">


```
Test Test [Equation]foo[/Equation], bar.

Test Test [Equation latex:"foo" /], bar.

[Equation]foo[/Equation], bar.

[Equation latex:"foo" /], bar.

[Equation]foo[/Equation], bar.
[Equation latex:"foo" /], bar.
```

**Comment by rreusser** [comment]
Apologies, you're correct. My mistake. I must not have noticed it before. At any rate, I think the space is probably undesirable. I wonder if maybe the problem is [here](https://github.com/idyll-lang/idyll-default-components/blob/master/components/equation.js#L106-L109):

```jsx
    return (
      <span>
          <Latex displayMode={this.props.display}>{latexString}</Latex>
          {this.renderEditing()}
      </span>
    );
```

I suspect maybe that should be:

```jsx
    return (<span><Latex displayMode={this.props.display}>{latexString}</Latex>{this.renderEditing()}</span>);
```

Which is to say, html is weird about line breaks after spans.

**Comment by rreusser** [comment]
Figured it out. PR to follow shortly.
